### ISSUE TITLE
Error on extracting spectograms

### ISSUE THREAD

**Issue by AC82-AI** [Danand/audio-sample-generator#1]
- Just one audio file loaded
- Click Extract button
- Error below
Couldn't find appropriate backend to handle uri UploadedFile(file_id='96b45cc6-7377-4560-820c-00ca68333dd1', name='ARABIANLOOPS0004.wav', type='audio/wav', size=792446, _file_urls=file_id: "96b45cc6-7377-4560-820c-00ca68333dd1" upload_url: "/_stcore/upload_file/0ccd3776-4519-48cb-bc06-2304209384cb/96b45cc6-7377-4560-820c-00ca68333dd1" delete_url: "/_stcore/upload_file/0ccd3776-4519-48cb-bc06-2304209384cb/96b45cc6-7377-4560-820c-00ca68333dd1" ) and format None.

WAV file is a 44.100Hz 24bit Stereo WAV File

**Comment by rei-koshka** [comment]
@AC82-AI
Hi! Could you provide some details?
- OS
- Python version

**Comment by AC82-AI** [comment]
Yep sure. 
- macOS Ventura 13.5
- Python 3.10.11

**Comment by rei-koshka** [comment]
@AC82-AI 
So, I tried to fix it. You could pull latest commits and check if error was fixed. 

Btw, if error still persists, you could try to install `ffmpeg`:

```bash
brew install ffmpeg
```

**Comment by AC82-AI** [comment]
Thanks @Danand unfortunately nothing changes with the latest pull. Also tried to install ffmpeg, requirement was already satisified.
Please ask for any other relevant detail for more investigations. Thanks.

**Comment by rei-koshka** [comment]
@AC82-AI 
Okay, let's try to figure out what went wrong!  
Could you enter the following commands and attach file `info.log` here?

```bash
cd audio-sample-generator # Change directory to your location of this repo.
ffmpeg > info.log 2>&1
source .venv/bin/activate
pip freeze >> info.log
python -c "from torchaudio._backend.utils import get_available_backends; print(get_available_backends())" >> info.log
```

**Comment by AC82-AI** [comment]
Sorry for the delay, sure, attached the file.
[info.log](https://github.com/Danand/audio-sample-generator/files/14746544/info.log)

**Comment by rei-koshka** [comment]
@AC82-AI
Hi!

I didn't reproduced this error, but I've tried to fix missing backends with own implementation of exact function needed.

You could check if it works now with pulling the latest commit (0ab7af29e925460e4da29f5451a4322bf6f7be4d).

**Comment by AC82-AI** [comment]
Thanks @Danand it worked perfectly! Now I'm locked on Train Lora step but I would open another issue.
Thanks again.
