### ISSUE TITLE
ModuleNotFoundError: No module named 'sd_scripts.ui' on Train LoRA

### ISSUE THREAD

**Issue by AC82-AI** [Danand/audio-sample-generator#2]
Hi @Danand it's me again, now I'm just struggling at the Train LoRA with this error: ModuleNotFoundError: No module named 'sd_scripts.ui' as I'll switch to the Train LoRA tab

**Comment by rei-koshka** [comment]
@AC82-AI 
Hi!  
Fixed it, I guess. You could pull the latest commit and check.

**Comment by AC82-AI** [comment]
Thanks @Danand you did it again. Now something during the train went wrong. I'll open another issue.
